"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # اتأكد إنك عامل import للـ os في أول الملف فوق خالص
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1aujv7$t^fkxw6+_46_b4jfve7@*-fl*fx-g@arf3^pk32ye!e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookings',
    'django_filters',
    'rest_framework', 
    'djoser',
    'rest_framework_simplejwt',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default="postgresql://postgres:awabmo132@@localhost:5432/pitch_booking",
        conn_max_age=600,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# الرابط اللي حيظهر في الـ API عشان نعرض بيه الصورة (مثال: /media/products/image.png)
MEDIA_URL = '/media/'
# المكان الفعلي اللي حتتخزن فيه الصور جوه مجلد المشروع
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    
    # 2. بنحدد عدد المنتجات في كل صفحة (مثلاً 10 منتجات)
    'PAGE_SIZE': 4,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

# قوانين الجوازات (Simple JWT)
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',), # الموبايل لازم يكتب كلمة JWT قبل التذكرة في الهيدر
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # (للتطوير خليها يوم عشان ما تتعب، في الإنتاج بنخليها دقايق)
}

# قوانين المقاول (Djoser)
DJOSER = {
    # 'LOGIN_FIELD': 'email', # لو الموديل بتاعك بيسجل بالإيميل مش اليوزرنيم
    # 'USER_CREATE_PASSWORD_RETYPE': True, # بيجبر المستخدم يكتب الباسورد مرتين عند التسجيل للتأكيد
    'SERIALIZERS': {
        # 1. المترجم المسؤول عن استقبال داتا التسجيل (إنشاء الحساب)
        'user_create': 'accounts.serializers.CustomUserCreateSerializer',
        
        # 2. المترجم المسؤول عن عرض بيانات المستخدم في أي حتة
        'user': 'accounts.serializers.CustomUserSerializer',
        
        # 3. المترجم المسؤول عن عرض بيانات المستخدم الحالي لما يطلب صفحة /me/
        'current_user': 'accounts.serializers.CustomUserSerializer',
    }
}

import os

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")