# Generated by Django 5.2.15 on 2026-06-30 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الملعب')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر في الساعة')),
                ('image', models.ImageField(upload_to='pitches_images/', verbose_name='صورة الملعب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الملعب')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(verbose_name='وقت النهاية')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Confirmed', 'مؤكد'), ('Canceled', 'ملغي')], default='Pending', max_length=20, verbose_name='حالة الحجز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.pitch')),
            ],
        ),
    ]
