# Generated by Django 5.2.15 on 2026-07-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Completed', 'مكتمل'), ('Failed', 'فشل')], default='Pending', max_length=20, verbose_name='حالة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المعاملة')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
        ),
    ]
